### ISSUE TITLE
loadAllTypekitsForModel takes too long when called for the first time

### ISSUE THREAD

**Issue by dmronga** [rock-cpp/orocos_cpp#15]
The call to loadAllTypekitsForModel() takes on my desktop PC around 11 seconds when being used for the first time in a program. The reason is the initialization of PkgConfigRegistry. Here, all search paths in PKG_CONFIG_PATH are scanned for .pc files and all .pc files are actually opened and parsed (see [here](https://github.com/rock-cpp/orocos_cpp/blob/e4ff47f326e90c29939baedb5e85e7cab4f84487/src/PkgConfigRegistry.cpp#L60)). Depending on your installation this may be 1000 or more files. 

Before, only the .pc file for the given model was opened and parsed. Eventually we have to fall back to a similar solution, although it means that we have to do File I/O at runtime...

**Comment by dmronga** [comment]
@maltewi

**Comment by jmachowinski** [comment]
This is sort of funny, I just looked into the recent changes.
In the first iteration, I used a global registry, like the one recently added,
and then switched to runtime opening because of performance issues...

**Comment by maltewi** [comment]
### These tools call initialize and have the following requirements:
* xec: whitelist or don't pre-load
* rock-launch: don't pre-load
* rock-runtime: pre-load all needed or all required for rock

### Options to improve
1. Don't load all PKGConfig files, but only those that actually belong to Rock components
2. Only load those files, that actually will be required for your application -->load them from a whitelist
3. Have a 'don't pre-load mode'
4. xec should not require to re-init on every program call (but this is an xec-issue, just here to keep in mind)

**Comment by maltewi** [comment]
### Plenty of PkgConfig files as test data
[pkgconfig_rock.zip](https://github.com/rock-cpp/orocos_cpp/files/3646143/pkgconfig_rock.zip)
[ros_pkgconfig.zip](https://github.com/rock-cpp/orocos_cpp/files/3646144/ros_pkgconfig.zip)
[ros_pkgconfig2.zip](https://github.com/rock-cpp/orocos_cpp/files/3646145/ros_pkgconfig2.zip)
[ros_pkgconfig_3.zip](https://github.com/rock-cpp/orocos_cpp/files/3646146/ros_pkgconfig_3.zip)
[rock_local_install.zip](https://github.com/rock-cpp/orocos_cpp/files/3646180/rock_local_install.zip)

### Benchmark
##### Many, many PkgConfig
```bash
wirkus@MWIRKUS-LAP-U:compositions[master]$ time PKG_CONFIG_PATH=/media/wirkus/Data/development/rock-runtime/install/lib/pkgconfig:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/pkgconfig_rock:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig2:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig3 rock-launch halt.yml 

Transition finished.

real	0m5,357s
user	0m3,989s
sys	0m0,050s
```
##### Not that  many PkgConfig
```bash
wirkus@MWIRKUS-LAP-U:compositions[master]$ time PKG_CONFIG_PATH=/media/wirkus/Data/development/rock-runtime/install/lib/pkgconfig rock-launch halt.yml 

Transition finished.

real	0m2,365s
user	0m0,857s
sys	0m0,054s
```
Benchmark done with DEBUG build.

##### Valgrind Performance analysis
###### Overall fuction costs
![image](https://user-images.githubusercontent.com/8180721/65497265-3bcbb500-deba-11e9-8563-dc81f174e8ab.png)

###### bool orocos_cpp::PkgConfigRegistry::addFile(const std::string &filepath)
![image](https://user-images.githubusercontent.com/8180721/65496952-b1835100-deb9-11e9-95eb-88c29dc4c7a6.png)

##### Conclusion from Experiment
Most cost is the loading of the PkgConfig files, but RegEx-Parsing takes 24.45%. <--- This can be reduced by:
1. Increase performance of RegEx. Here are some hints: https://www.loggly.com/blog/regexes-the-bad-better-best/
2. Don't identify all package types via RegEx. Instead only identify one package, e.g. OrogenProject. Then actively search for the other PkgConfig files that should match the naming conventions for the package types.

### Plan
* Benchmark after implementing Conclusion 2 from experiment.
* Create issue for student for Conclusion 1
* Investigate design for allowing 'don't pre-load' and ' whitelist' modes

**Comment by maltewi** [comment]
### Implemented Conclusion 2
The patch doesn't match every pkgconfig against different package types, but actively search if a orogen-project or deployment-package was identified. Deployment-packages are ideteifief by the `orogen-project--prefix, deployment packages by the `orogen-`-prefix.

#### Benchmark
##### Many, many PkgConfig
```
wirkus@MWIRKUS-LAP-U:compositions[master]$ time PKG_CONFIG_PATH=/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/pkgconfig_rock:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig2:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig3:/media/wirkus/Data/development/rock-runtime/install/lib/pkgconfig rock-launch halt.yml 

Transition finished.

real	0m3,442s
user	0m3,377s
sys	0m0,028s
```
**36% improvement**

##### Not so many PkgConfig
```
wirkus@MWIRKUS-LAP-U:compositions[master]$ time PKG_CONFIG_PATH=/media/wirkus/Data/development/rock-runtime/install/lib/pkgconfig rock-launch halt.yml 

Transition finished.

real	0m0,817s
user	0m0,765s
sys	0m0,024s
```
**85% improvement**

#### Next
Investigate design for allowing 'don't pre-load' and 'whitelist'-modes

**Comment by maltewi** [comment]
# Implemented whitelist model
Loading only 'std' typekit on startup for `rock-launch`

##### Many Many
```
time PKG_CONFIG_PATH=/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/pkgconfig_rock:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig2:/home/dfki.uni-bremen.de/wirkus/Desktop/pkgconfig/ros_pkgconfig3:/media/wirkus/Data/development/rock-runtime/install/lib/pkgconfig rock-launch halt.yml 
 
Transition finished.

real	0m0,541s
user	0m0,123s
sys	0m0,009s
```
##### Not so Many
```
wirkus@MWIRKUS-LAP-U:compositions[master]$ time PKG_CONFIG_PATH=/media/wirkus/Data/development/rock-runtime/install/lib/pkgconfig rock-launch halt.yml 

Transition finished.

real	0m0,525s
user	0m0,075s
sys	0m0,023s
```

**Comment by maltewi** [comment]
I assume that the implemented solution is ok. If no, please re-open
